### ISSUE TITLE
Cmd K option available for terminal

### ISSUE THREAD

**Issue by saltillokid11** [learn-co/learn-ide#106]
In some labs when running the learn command, it spits out a long list of pass/fail results. Since the terminal is a fixed window, when testing your code and running learn multiple times, it adds a long history of pass/fail results. Scrolling is very sensitive and it's easy to get lost what results you are looking at. "clear" command retains history. Cmd K should clear everything after the curser.

I'm not sure if this is feasible but a nice to have.

**Comment by drewprice** [comment]
could just be a key map that resets the emulator, though we would need to cache the prompt to bring it back after reset.

better yet, it could simply be a keymap that sends "clear\r" over the terminal websocket. just checked, and that definitely works.

**Comment by drewprice** [comment]
So, this would actually require a whole bunch of weird code. `cmd-k` is a [partially matched keymap](https://atom.io/docs/api/v1.14.2/KeymapManager), so we can't actually map anything to it without doing a big hacky workaround. As an alternative, I just added a `Clear terminal` option to the terminal's contextmenu, https://github.com/learn-co/learn-ide/pull/409/commits/9c764142dc6da5f47fd9ddb0b694304e55b376f9, which just send `^L` (ctrl-l) to the terminal.

**Comment by drewprice** [comment]
This was addressed (via the alternative mentioned up there :point_up:) in #409 an will be released with v2.5 🎉
