### ISSUE TITLE
Windows: for terminal, using up arrow to see command history freezes terminal

### ISSUE THREAD

**Issue by saltillokid11** [learn-co/learn-ide#130]
I tested this on the Windows 10 as this is the environment the student reported the issue.

To reproduce the issue: 
1) I had to run a number of commands in terminal, specifically the learn command several times. 
2) Click the up arrow to scroll through command history
3) After a certain amount the command line will lock/freeze

NOTE: you can still scroll in the terminal and you can still use the text editor, you just can't type any commands.

**Comment by joshrowley** [comment]
i don't believe this is an issue in v2, confirmed by a beta tester who had been experiencing this exact problem
