### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co/learn-ide#198]

**Comment by mike-north** [comment]
Are there still plans on allowing the IDE to work offline? Needing to have an internet connection just to run tests makes the experience of going through exercises quite frustrating at times.

CC: @lisaychuang

**Comment by meelos** [comment]
Yeah I'd +1 this in some way. I understand how important the online element is to this way of learning however being a bit of a globetrotter I find myself in many an internet blackspot. would be great to be able to progress in some manner between antennae. ;)
