### ISSUE TITLE
Linux: open in browser doesn't work

### ISSUE THREAD

**Issue by saltillokid11** [learn-co/learn-ide#261]
In linux IDE, right clicking file and selecting open in browser does nothing. I verified, chrome is default web browser. Checked in IDE console and it shows it's trying to open firefox.

![firefox](https://cloud.githubusercontent.com/assets/13110825/17154866/ca8d0c24-5350-11e6-9f0d-68448e72375e.png)

**Comment by drewprice** [comment]
closing—we kicked "open in browser" out of the IDE, though folks can add it back in with an atom package such as [open-in-browser](https://atom.io/packages/open-in-browser)
