### ISSUE TITLE
Chrome warns user IDE will harm computer

### ISSUE THREAD

**Issue by saltillokid11** [learn-co/learn-ide#264]
I know this was discussed in slack but never fully address as we assumed it was a new chrome feature (v51+), I just tested this on version 49 (ubuntu) and am getting the same warning.

![harm](https://cloud.githubusercontent.com/assets/13110825/17180631/1255effe-53eb-11e6-9be4-a2280020bd56.png)

cc @kvignali @loganhasson

**Comment by drewprice** [comment]
I don't think we've been seeing this with our new build? Going to close for now
