### ISSUE TITLE
Windows: Some students are getting errors in downloads

### ISSUE THREAD

**Issue by saltillokid11** [learn-co/learn-ide#281]
I think this is related to windows character path length limit and users with long usernames are getting this error or it could be related to spaces or weird characters in the username itself.

![image001](https://cloud.githubusercontent.com/assets/13110825/17781147/2542dfd4-653c-11e6-8238-14d1ca9a2786.jpg)

**Comment by drewprice** [comment]
closing, new installer with > 2.0
