### ISSUE TITLE
Windows: .atom installs in multiple user dir

### ISSUE THREAD

**Issue by saltillokid11** [learn-co/learn-ide#282]
Closing #204 in favor of this one.

For some windows machines that have multiple users, the IDE will sometimes split install the `.atom` in two different user dir.

I have 3 theories on what could cause this.
1. The IDE is installing alphabetically
2. Multiple users can be signed in (multiple sessions) at a time and the IDE installs by first login
3. IDE favors installing in admin dir

Still investigating.

**Comment by joshrowley** [comment]
we're no longer installing any files in the `.atom` directory so this shouldn't be an issue any more
