### ISSUE TITLE
Logging Tools

### ISSUE THREAD

**Issue by joshrowley** [learn-co/learn-ide#306]
Eventually I want to set up better logging and error reporting to help us when we need to debug student issues with the IDE.

I was lurking in the Atom Slack and people were mentioning [crashreporter](https://github.com/sdolard/node-crashreporter) and [winston](https://github.com/winstonjs/winston) for helping us with this.

Not v2 blocking, but something I think we should tackle sooner rather than later because it will help us with debugging.

**Comment by joshrowley** [comment]
bumping this into v2....debugging stuff on windows is very difficult and we need better insight from our tools on what's going on

**Comment by drewprice** [comment]
We moved away from winston, but we are still working on and thinking through how to appropriately log from the IDE.

**Comment by drewprice** [comment]
Keeping this open, but removing it from the v2 milestone

**Comment by joshrowley** [comment]
This project is no longer maintained.
