### ISSUE TITLE
Change wording when user can't open lesson

### ISSUE THREAD

**Issue by saltillokid11** [learn-co/learn-ide#308]
When student types Learn Open and can't open the lab, the current text shows:
`Looking for lesson...`
`Sorry, there seems to be a problem with this lesson. Please submit a bug report to bugs@learn.co`
`and try again later.`

Can we change this to:
`Looking for lesson...`
`Sorry, there seems to be a problem with this lesson. Please use the Ask A Question feature for chat support`

cc @kvignali

**Comment by drewprice** [comment]
gonna close, related to the gem
