### ISSUE TITLE
Need a fallback when the login window fails to load

### ISSUE THREAD

**Issue by notnotdrew** [learn-co/learn-ide#376]
As the IDE is dependent on being able to load https://learn.co/ide/sign_in before the login window will appear, we should create a fallback for when this page fails to load.

Otherwise, the IDE just opens up to an empty text editor and it's super confusing, especially for someone who has never used it.

**Comment by drewprice** [comment]
Currently [falling back on a github login](https://github.com/learn-co/learn-ide/blob/6cf86624065832d6a0461a928b616b6fdabebe65/lib/auth.js#L107-L110), which doesn't make sense for most people.
