### ISSUE TITLE
newest Learn IDE (Atom 2.2.1) tries to automatically download and install Atom 1.12.7

### ISSUE THREAD

**Issue by The-Alchemist** [learn-co/learn-ide#391]
# Screenshot
![image](https://cloud.githubusercontent.com/assets/812287/21276408/430445aa-c39f-11e6-8593-e6255a2af6d4.png)

# Description
When you click on "Restart and Install" above, it actually just shuts down (i.e., never restarts).  When you manually open it back up, it'll actually try to download 1.12.7 and you're stuck in a loop.

**Comment by drewprice** [comment]
thanks for reporting this! we've resolved it with the latest release (primarily by simply removing the [about](https://github.com/atom/about) package from the core build of the Learn IDE
