### ISSUE TITLE
fs connects improperly

### ISSUE THREAD

**Issue by drewprice** [learn-co/learn-ide#397]
Occasionally (I _think_ when multiple windows are involved) the IDE will establish a working terminal connection, and appears to open a fs websocket as well, but the fs websocket never receives a `ready` message, nor does it respond to follow up messages sent from the client.

When combined with https://github.com/learn-co/nsync-fs/issues/12, the blue "Loading your code" when will appear and just hang around forever (or until you quit & restart the IDE). Not sure if it happens without the combination of https://github.com/learn-co/nsync-fs/issues/12.

cc @aturkewi

**Comment by drewprice** [comment]
This may actually only happen if a given oauth key is connected, and then tries to connect from another computer at the same time...

**Comment by aturkewi** [comment]
I'm pretty sure I've seen it hang out "Loading your code" a bunch and I probably only have an IDE on one other computer that is rarely if ever on.

**Comment by drewprice** [comment]
This is something to keep an eye on with [2.5.0](https://github.com/learn-co/learn-ide/releases/tag/v2.5.0-beta0)—I've put something in that I think may help (https://github.com/learn-co/learn-ide-tree/pull/48)
