### ISSUE TITLE
After installation, multiple instances loaded

### ISSUE THREAD

**Issue by crimpy** [learn-co/learn-ide#400]
I installed the PC version on two different systems after uninstall of the original. Once the installation process was complete, the Atom IDE launched multiple instances. On my first machine, it launched around 7 instances, on my second install (different machine) it launched multiple. I had to select all of the instances in the task manager and kill them all so it wouldn't continue to launch new instances.

**Comment by kvignali** [comment]
@crimpy which version of the IDE are you using? https://help.learn.co/hc/en-us/articles/236010267-How-to-check-your-IDE-version-

**Comment by crimpy** [comment]
I am using the beta test version 2.3.3 found here: https://github.com/learn-co/learn-ide/releases/tag/v2.3.3

**Comment by kvignali** [comment]
thanks!

**Comment by drewprice** [comment]
addressed in v2.4.0—with the new build on Atom@1.14.2, we've configured it to open only one window on launch by default.
