### ISSUE TITLE
Learn IDE is sending exceptions to Atom

### ISSUE THREAD

**Issue by 50Wliu** [learn-co/learn-ide#416]
Hi, Atom maintainer here.  We're receiving uncaught exceptions from Learn IDE (see https://github.com/search?q=org%3Aatom+learn-ide&type=Issues), which I think is detrimental for the both of us, because we can't do anything about them, and you're not receiving them.  So I would suggest bundling a custom version of the [Notifications](https://github.com/atom/notifications) package such that it reports issues here by default instead of to Atom.

**Comment by drewprice** [comment]
🤦‍♂️ Thanks for bringing this up! I'll copy those issues over, and we'll work on taking care of this.
