### ISSUE TITLE
learn-test dies silently

### ISSUE THREAD

**Issue by WilliamBarela** [learn-co/learn-ide#428]
![learn-ide-silent](https://cloud.githubusercontent.com/assets/21199528/24433979/82dd4726-1467-11e7-82e5-918393497891.jpg)

When using the Learn IDE, sporadically after running learn-test on the user's Learn remote profile, the tests will pass, but the Learn.co server is not updated with the information of those tests passing (please see output of learn-status above). If one runs learn-submit, a pull request is then successfully made to Github, but again, Learn.co server is not updated. As a result, when learn-test finally passes, the student has to delete remote repository and refork to get learn-submit to work (due to the previous pull request).

I am not sure what the issue is for the connect between Learn.co server and the user's Learn-IDE remote profile. This should be corrected. But for now, to help the students, it would be good to add feedback about the status of updating the local tests to the Learn.co server. If this fails, there should be a fail-safe to stop the 'pull request' to Github when learn-submit is run so that the student doesn't have to delete the repo.

Thank you!

**Comment by WilliamBarela** [comment]
https://github.com/WilliamBarela/oo-basics-with-class-constants-v-000/blob/master/learn-server-problem.txt

This is a file which is the output of another time this occurred.

**Comment by drewprice** [comment]
Issue moved to [learn-co/learn-co #75](https://github.com/learn-co/learn-co/issues/75) via [**ZenHub**](https://www.zenhub.com/)
