### ISSUE TITLE
New file not showing up in tree view

### ISSUE THREAD

**Issue by jcpny1** [learn-co/learn-ide#433]
Windows 10/IDE 2.4.2
Created a file in app/views/ingredients. Shows up in ls -l listing, but not in tree view. If I reconnect IDE, it still doesn't show up. If I exit IDE and restart it, the file will appear in the tree view.

**Comment by drewprice** [comment]
Issue moved to [learn-co/nsync-fs #15](https://github.com/learn-co/nsync-fs/issues/15) via [**ZenHub**](https://www.zenhub.com/)
