### ISSUE TITLE
IDE console very narrow, runs off bottom of screen

### ISSUE THREAD

**Issue by jcpny1** [learn-co/learn-ide#434]
Windows 10, IDE 2.4.2.
When I start the IDE from desktop shortcut, the console appears to have a width of about 40 characters.
Sometimes, the console input prompt and last line of output are below the bottom of screen and are not visible until I hit Enter a few times to bring into view.
Some weird wrapping going on (ls -l):
ttt-2-board-rb-bootcamp-prep-
000                                                                                                                                    
ttt-3-display_board-example-bootcamp-prep-
000                                                                                                                       
ttt-4-display-board-rb-bootcamp-prep-
000                                                                                                                            
validations-in-controller-actions-rails-lab-v-
000                                                                                                                   
validations-with-form_tag-rails-lab-v-
000                                              

Problem clears up if I select menu item Packages/Learn IDE/Reconnect.

**Comment by drewprice** [comment]
This is the primary issue we're targeting in [v2.5.0](https://github.com/learn-co/learn-ide/releases/tag/v2.5.0-beta0) 🎉
