### ISSUE TITLE
Repository disappears

### ISSUE THREAD

**Issue by jcpny1** [learn-co/learn-ide#435]
Windows 10, IDE 2.4.2.
Opened rails-programmer-profile-partials-v-000 via website.
Ran rake db_migrates and db:seed.
Ran rails s from console.
While browsing the data, IDE disconnected and rails server exited.
Cloned repository disappeared from tree view.
Re-opened from website which initiated re-cloning. Only this time, the app directory was completely empty and databases were gone.
Output of ps command showed this (which looks like too many processes):
  PID TTY          TIME CMD                                                                                                               
   46 console  00:00:00 bash                                                                                                              
  125 console  00:00:00 learn                                                                                                             
  132 console  00:00:00 ruby                                                                                                              
  136 console  00:00:00 bash                                                                                                              
13276 console  00:00:00 learn                                                                                                             
13283 console  00:00:00 ruby                                                                                                              
13287 console  00:00:00 bash                                                                                                              
13369 console  00:00:00 ps

**Comment by drewprice** [comment]
@jcpny1 apologies for the delay.

Just to be clear, how did the IDE disconnect? If it disconnects, your entire terminal session should close, not just the rails server.

Also, if the repo had to be cloned again then there database would need to be seeded again, so this may be closer to the problem.

**Comment by jcpny1** [comment]
A status of Disconnected appears in a popup, the normally green Learn status in the lower right corner turns red, and the treeview and save commands become unresponsive. How did it disconnect? I suspect an unreliable IDE or IDE server service as my internet connect appears to be rock solid.

Bottom line: when this error occurred, each reconnect to the server produced a different result as described in original description. A cloned repository should stay cloned.
