### ISSUE TITLE
Simple notifications

### ISSUE THREAD

**Issue by drewprice** [learn-co/learn-ide#442]
An idea to send messages to IDE users:

Create an endpoint on learn that returns something like
```JSON
{ 
  "message": "Hello there",
  "options": {},
  "expires":  "datestring"
}
```
Where `options` correspond to the options defined for [notifications](https://atom.io/docs/api/v1.14.4/NotificationManager#instance-addInfo) (replacing `button[onDidClick]` with something like `button[url]`, and if provided the button just opens the url).

On the client, we check the endpoint maybe every hour. The first time we get a message, we calculate & store a hash of it. Whenever the hash is broken, as long as it hasn't expired, we pop it open.

Alternatively we send an `id` rather than hashing or something.

**Comment by joshrowley** [comment]
Maybe not for this PR / release cycle, but I think it'd be also nice to be able to send a type of message that opens up a pop up (the endpoint can have width and height dimensions and then a default) with any URL we want to send students to, that way we have a lot of flexibility.
