### ISSUE TITLE
editor crashed after popping out the terminal

### ISSUE THREAD

**Issue by kvignali** [learn-co/learn-ide#465]
1. I popped out the terminal
2. The editor stopped responding:
<img width="1026" alt="screen shot 2017-05-17 at 4 38 51 pm" src="https://cloud.githubusercontent.com/assets/2243896/26175112/94940322-3b1f-11e7-8073-4a30b645a487.png">

3. I closed the IDE
4. Reopened it and the terminal prompt wasn't there:
![screen shot 2017-05-17 at 4 39 56 pm](https://cloud.githubusercontent.com/assets/2243896/26175141/ab2ada16-3b1f-11e7-89bc-29d4992c8216.png)
5. ran `learn` and the prompt appeared after running the tests

**Comment by kvignali** [comment]
able to consistently repro

**Comment by drewprice** [comment]
@kvignali let's look at this one together—I'm unable to reproduce it.
