### ISSUE TITLE
git push failing 2 out of 3 and 3 out of 4 attempts.

### ISSUE THREAD

**Issue by jcpny1** [learn-co/learn-ide#472]
I forked and cloned a lesson (e.g., javascript-lodash-templates-v-000). Made and committed changes. When I go to 'git push origin master', git asks for my username and password. For the first two of three attempts, I get this response:
```
Username for 'https://github.com': jcpny1
Password for 'https://jcpny1@github.com':
remote: Invalid username or password. 
fatal: Authentication failed for 'https://github.com/jcpny1/javascript-lodash-templates-v-000.git/'
```
On the third attempt, success. I am 100% percent sure that I am entering the correct credentials.
For the next repository updated, commit failed for the first three attempts; succeeded on the fourth.
Windows 10, IDE 2.4.2 freshly downloaded within 48 hours.

**Comment by drewprice** [comment]
Thanks for reporting @jcpny1. Unfortunately, this is very unlikely to be related to anything on the Learn IDE client, or the IDE server. I'll go ahead and close this for now unless we are able to spot anything that makes us think otherwise.
