### ISSUE TITLE
Terminal text font is too dark and thin

### ISSUE THREAD

**Issue by howardbdev** [learn-co/learn-ide#474]
The new font in the terminal window is too dark and thin which makes it hard to read without cranking up the screen brightness (which then makes all other windows too bright).

**Comment by drewprice** [comment]
Hey @howardbdev—with `2.5.0-beta0` you can actually configure all of the terminal colors from the package settings, ie `File > Settings > Packages > Learn IDE`.

With #478—which I've just added for the next upcoming beta release, `2.5.0-beta1`—you will also be able to specify a font family to use if you'd prefer something thicker (I really dig [hack](http://sourcefoundry.org/hack/)).

**Comment by howardbdev** [comment]
Drew,

This is awesome, thank you!!!!

I will look forward to playing with the font as well!

Howard
