### ISSUE TITLE
unable to fuzzy find file in current directory

### ISSUE THREAD

**Issue by ktravers** [learn-co/learn-ide#475]
attempting to open file using `command + t` fuzzy find shortcut. file search is not returning files that exist in current directory.

lesson: `javascript-intro-to-functions-lab-vfa-2017`

![find](https://cloud.githubusercontent.com/assets/8152930/26318068/d1b83e82-3ee7-11e7-842b-2f9cbab61876.gif)

**Comment by ktravers** [comment]
update: issue is intermittent (yay!)

i switched batches and opened the same lab in a different batch/track (`javascript-intro-to-functions-lab-v-000`). then i was able to `command + t` find any file in my current directory and recently opened files.

![find2](https://cloud.githubusercontent.com/assets/8152930/26318550/855f5d8e-3ee9-11e7-82f0-353b55a7da0f.gif)

**Comment by drewprice** [comment]
Noticed first in 2.5.0-beta0 but I would guess this has likely been an intermittent issue for a while... possibly related files appearing on the local disk after fuzzy search has indexed them? That's a total guess though, I don't know how Atom's fuzzy search works.

**Comment by drewprice** [comment]
somewhat related: #396
