### ISSUE TITLE
Changes to index.js in IDE not showing up in browser.

### ISSUE THREAD

**Issue by jcpny1** [learn-co/learn-ide#476]
until IDE was restarted. Then changes began to show up.

**Comment by jcpny1** [comment]
resolved with restart of IDE (and httpserver), then refresh browser window. Next time, suggestion is to try Chrome 'Hard Reload'.

**Comment by drewprice** [comment]
@jcpny1 This is unrelated to the Learn IDE, but be sure to raise questions like this one using the "Ask a Question" on Learn feature to get real-time help from a technical coach.
