### ISSUE TITLE
Any way to assign hotkeys to switch between atom and the console within the IDE?

### ISSUE THREAD

**Issue by meelos** [learn-co/learn-ide#479]
Not a priority I know, but would be a little UX tweak that could add up in terms of efficiency. :)

**Comment by drewprice** [comment]
Hey @meelos! This exists with the current release, but only if you are on a mac (`cmd + ;` will do it).

In `2.5.0`, which is currently in beta but will be released within the next week, this shortcut is extended to windows & linux (`ctrl + ;` for these platforms).

There are a couple other shortcuts we've added (toggling the terminal's visibility, and toggling the popout terminal) and you can see them all listed out on the package's settings page (on mac: `Learn IDE > Preferences > Packages > Learn IDE`, or on Windows & Linux `File > Settings > Packages > Learn IDE`).

Let us know if there is anything else we can add that would be helpful!
