### ISSUE TITLE
Scrolling shortcuts not working

### ISSUE THREAD

**Issue by aturkewi** [learn-co/learn-ide#484]
From https://flatiron.atlassian.net/browse/TS-359
The shortcuts per the help center article (http://help.learn.co/the-learn-ide/the-basics-of-the-learn-ide/how-to-scroll-in-the-ide) are:
Windows
`ctrl + up/down` - To scroll up or down one line at a time in the terminal
`shift + pageUp/pageDown` - To scroll up or down a full 'page' (a 'page' being the amount of lines you can see in the terminal at one time)
Mac
`ctrl + alt + up/down`  - To scroll up or down one line at a time in the terminal
`fn + shift + up/down`  - To scroll up or down a full 'page' (a 'page' being the amount of lines you can see in the terminal at one time)

`ctrl` + `up/down` is not scrolling in the IDE for a student on windows (not sure which version, but would love get see more data on this if more ppl see it). 

`ctrl + alt + up/down` is not working on my mac (10.12.5) running IDE 2.5.2

**Comment by aturkewi** [comment]
Note, user seeing the windows issue was `devonjboen`

**Comment by kvignali** [comment]
@aturkewi this functionality was removed in the latest version, and will be added back in to the next version. My understanding is that this is not a blocking feature. cc @drewprice @StevenNunez

**Comment by drewprice** [comment]
@aturkewi thanks for the details.

I did some quick digging to see where we lost this, but haven't spotted it yet. My initial thought was that we had patched something into the legacy terminal view, [lib/views/terminal.coffee](https://github.com/learn-co/learn-ide/blob/v2.4.2/lib/views/terminal.coffee), but I'm not seeing it there.

It definitely wasn't anything we had registered as a keymap, for any platform, through Atom. Wondering if it was possibly a feature of [`term.js`](https://github.com/chjj/term.js/), the old terminal emulator—though I'm not seeing any signs of it there either with just a quick scan of the repo.

At any rate, it's something we should be able to build out (with proper keymaps) with xterm: https://xtermjs.org/docs/api/terminal/#scrolldispn

**Comment by aturkewi** [comment]
Sounds good! I know that of the two scroll commands on mac per the article, only one works. Do any of the scroll commands still work for windows? As long as there is _some_ way to scroll in the terminal using the keyboard, I don't think it's blocking, but if the only way to scroll is with a mouse or track pad, I think that may be an issues. I don't think it's safe to assume everyone has a mouse with a scroll wheel, and I've never found track pad scrolling to be any good on anything besides a mac.

**Comment by drewprice** [comment]
@aturkewi I don't think the keyboard scrolling works on Windows; however, the new emulator should display a scroll bar when there are unseen rows that folks can click and drag to see more.

**Comment by drewprice** [comment]
Will go out in `v2.5.3`
