### ISSUE TITLE
IDE initializes with the bottom line below the bottom of the window

### ISSUE THREAD

**Issue by kkterai** [learn-co/learn-ide#489]
Cannot view bottom or type on bottom line of the IDE.
![capture2](https://user-images.githubusercontent.com/19792273/27144772-0208ec1e-50e8-11e7-8540-f926be5ba254.png)

**Comment by drewprice** [comment]
@kkterai do we know what version this user was on? it looks like they may still be on something < v2.5

This is the very issue 2.5 was aiming to address, so I certainly hope they are on older version 😬

**Comment by kkterai** [comment]
@drewprice they are on v.2.5.2
![capture](https://user-images.githubusercontent.com/19792273/27232304-6ecf6782-526a-11e7-99eb-dd3be9217b96.png)

**Comment by jcpny1** [comment]
Still a problem 2.5.3
