### ISSUE TITLE
Revise text in Learn IDE notification, "loading your remote code"

### ISSUE THREAD

**Issue by kkterai** [learn-co/learn-ide#509]
The current message says, "This may take a moment but will happen very occasionally (maybe just once)" (see screenshot, below).

Loading remote code may happen multiple times when students are experiencing difficulty with IDE connectivity. This message may appear several times, and can add to frustration with Learn because the reload is not actually happening "very occasionally."

A possible option is to eliminate the supplementary text altogether so it just reads, "Learn IDE: loading your remote code."

<img width="263" alt="screen shot 2017-07-19 at 8 52 43 am" src="https://user-images.githubusercontent.com/19792273/28378669-d2b977aa-6c65-11e7-881b-2cece2f302d3.png">

**Comment by drewprice** [comment]
Good call 👍 

`(maybe just once)` is short for "I did this cool caching thing so that, theoretically, we only have to do this one time, but you know, computers, right? 🤷‍♂️ " Which, uh, is... yeah, probably not that fun to see when the "cool caching thing" is not working 😬 ☹️
