### ISSUE TITLE
/etc/localtime other than UTC?

### ISSUE THREAD

**Issue by asiplas** [learn-co/learn-ide#527]
A student in https://learn.co/tracks/bootcamp-prep brought up his disdain for the UTC time in the IDE's Shell and wanted to know how to change to local time.  `/etc/localtime` within IDE environment references UTC and perhaps could reconfigure that somehow; otherwise suppose could simply export [PS1](https://www.linuxnix.com/linuxunix-shell-ps1-prompt-explained-in-detail/) to not contain time.

Any ideas on this? Question went unresolved there…

**Comment by asabogal** [comment]
In the IDE terminal, use the command: tzselect
Then follow the prompt directions and permanently set the timezone on your home directory.
